name: Sync templates with Fiberplane

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync templates
        uses: fiberplane/sync-templates@initial
        with:
          api-token: ${{ secrets.FP_TOKEN }}
          workspace-id: ${{ secrets.FP_WORKSPACE_ID }}
          fp-base-url: https://demo.fiberplane.io

